version: '3'

services: 
    back: 
        build: 
            context: .
            dockerfile: back.Dockerfile
        volumes: 
            - /back:/app
        networks: 
            - bridge
    front: 
        build: 
            context: .
            dockerfile: front.Dockerfile
        volumes: 
            - /front:/app
        ports: 
            - 8080:8080
        networks: 
            - bridge
networks:
    bridge:
     