version: '3'

services: 
    back: 
        build: 
            context: back/
            dockerfile: back.Dockerfile
        networks: 
            - bridge
        restart: always
    front: 
        build: 
            context: front/
            dockerfile: front.Dockerfile
        ports: 
            - 8080:8080
        volumes: 
            - .front/app/:/app
        networks: 
            - bridge
        restart: always

networks:
    bridge:
     